version: '3'

services:
  nats-server:
    image: nats:latest # Ocupar versiones específicas cuando se trabaje en proyecto real
    ports:
      - 8222:8222

  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
      args:
        - PORT=${GATEWAY_PORT}
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  products-ms:
    build:
      context: ./products-microservice
      dockerfile: dockerfile
      args:
        - PORT=${PRODUCTS_MICROSERVICE_PORT}
    ports:
      - ${PRODUCTS_MICROSERVICE_PORT}:${PRODUCTS_MICROSERVICE_PORT}
    volumes:
      - ./products-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PRODUCTS_MICROSERVICE_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}

  auth-ms:
    build:
      context: ./auth-microservice
      dockerfile: dockerfile
      args:
        - PORT=${AUTH_MICROSERVICE_PORT}
    ports:
      - ${AUTH_MICROSERVICE_PORT}:${AUTH_MICROSERVICE_PORT}
    volumes:
      - ./products-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${AUTH_MICROSERVICE_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
