version: '3'

services:
  nats-server:
    image: nats:latest # Ocupar versiones específicas cuando se trabaje en proyecto real
    ports:
      - 8222:8222

  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile.prod
      args:
        - PORT=${GATEWAY_PORT}
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-450513/image-registry/client-gateway
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      - PORT=${GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  products-ms:
    build:
      context: ./products-microservice
      dockerfile: dockerfile.prod
      args:
        - PORT=${PRODUCTS_MICROSERVICE_PORT}
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-450513/image-registry/products-ms
    environment:
      - PORT=${PRODUCTS_MICROSERVICE_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}

  auth-ms:
    build:
      context: ./auth-microservice
      dockerfile: dockerfile.prod
      args:
        - PORT=${AUTH_MICROSERVICE_PORT}
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-450513/image-registry/auth-ms
    environment:
      - PORT=${AUTH_MICROSERVICE_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  payments-ms:
    build:
      context: ./payments-microservice
      dockerfile: dockerfile.prod
      args:
        - PORT=${PAYMENTS_MICROSERVICE_PORT}
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-450513/image-registry/payments-ms
    ports:
      - ${PAYMENTS_MICROSERVICE_PORT}:${PAYMENTS_MICROSERVICE_PORT}
    environment:
      - PORT=${PAYMENTS_MICROSERVICE_PORT}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - NATS_SERVERS=${NATS_SERVERS}

  orders-ms:
    build:
      context: ./orders-microservice
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-450513/image-registry/orders-ms
    environment:
      - PORT=${ORDERS_MICROSERVICE_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${ORDERS_DATABASE_URL}
